name: todo_app
description: ToDo application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  get: ^4.6.5

  # Local data base
  sqflite: ^2.0.3

  # Video player
  chewie: ^1.3.4
  video_player: ^2.4.5

  # UI
  overlay_support: ^2.0.1
  cupertino_icons: ^1.0.5

  # Utils
  mime: ^1.0.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  web: true
  ios: true
  macos: true
  linux: true
  windows: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'
  image_path: 'assets/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
